export const SAMPLE_PROMPTS = [
  'In the midst of a bustling city, where skyscrapers towered over the streets, a young artist found solace in painting colorful murals on the sides of abandoned buildings.',
  'After months of planning and anticipation, the group of friends embarked on a cross-country road trip, eager to explore the stunning landscapes and hidden gems along the way.',
  'As the sun set behind the mountains, casting a warm golden glow over the meadow, families gathered around a crackling bonfire, roasting marshmallows and sharing stories.',
  'With a heart full of determination and a mind brimming with ideas, she embarked on a journey to start her own business, overcoming obstacles and embracing the thrill of entrepreneurship.',
  'The ancient castle, perched on a hilltop overlooking the vast expanse of the countryside, whispered stories of knights and kings from centuries long gone.',
  'The astronaut floated weightlessly inside the space station, marveling at the breathtaking view of Earth from above, a tiny blue dot suspended in the vastness of the universe.',
  "As the orchestra played the opening notes, the conductor's baton gracefully danced through the air, guiding the musicians in perfect harmony, captivating the audience with the symphony's beauty.",
  'In the heart of the rainforest, surrounded by lush green foliage and the gentle hum of exotic creatures, a team of scientists discovered a rare species previously unknown to the world.',
  'After hours of meticulous preparation, the chef presented a masterpiece on the plate, a culinary work of art that delighted the senses and transported diners to a world of exquisite flavors.',
  'The historic novel transported readers back in time, weaving a tapestry of vivid characters and gripping plotlines that illuminated the triumphs and struggles of a bygone era.',
  'The thunderous applause erupted as the athlete broke the world record, shattering barriers and proving that with unwavering dedication and relentless effort, anything is possible.',
  'In the depths of the ocean, hidden beneath layers of coral and vibrant marine life, divers discovered a shipwreck laden with treasures, whispering tales of pirates and lost fortunes.',
  'The sprawling vineyard, bathed in golden sunlight, stretched as far as the eye could see, its rows of grapes promising the creation of exquisite wines that would delight connoisseurs.',
  'Against the backdrop of a picturesque sunset, a couple exchanged heartfelt vows, promising to love and cherish each other for a lifetime, surrounded by the love and support of their family and friends.',
  'The passionate orator stood on the stage, delivering a powerful speech that resonated with the audience, igniting a spark of inspiration and calling for positive change in the world.',
  'The bustling marketplace teemed with vibrant colors, exotic aromas, and the sound of enthusiastic bartering, as locals and tourists alike immersed themselves in the rich tapestry of a foreign culture.',
  'Nestled in the embrace of towering mountains, the quaint village exuded an old-world charm, with its cobblestone streets, cozy cafes, and friendly locals welcoming visitors with open arms.',
  'The vast savannah stretched endlessly, dotted with majestic wildlife roaming freely, as a safari jeep traversed the rugged terrain, offering a glimpse into the wonders of the natural world.',
  'The intricate dance performance unfolded on stage, as dancers moved with grace and precision, their synchronized movements telling a story that transcended language and touched the depths of the soul.',
  'The old diary, discovered in the attic, revealed the poignant reflections and intimate thoughts of its writer, transporting the reader on a nostalgic journey through a bygone era.',
  'The majestic waterfall cascaded down the rocky cliffs, creating a mesmerizing display of power and beauty.',
  'In the quiet solitude of the forest, sunlight filtered through the canopy, casting a magical glow on the moss-covered ground.',
  'The laughter of children echoed through the playground as they swung on swings and climbed on the jungle gym.',
  'The old, weathered lighthouse stood tall on the rugged coastline, guiding ships safely through the treacherous waters.',
  'As the gentle breeze rustled the leaves of the trees, a sense of tranquility settled over the peaceful garden.',
  'The vibrant city pulsated with energy, as people hurriedly went about their daily lives amidst the towering skyscrapers.',
  'The painter meticulously applied brushstrokes to the canvas, bringing to life a breathtaking landscape filled with vivid colors.',
  'The sound of waves crashing against the shore provided a soothing soundtrack to the beachgoers lounging on the sand.',
  'Amidst fields of blooming flowers, butterflies danced and fluttered, adding a touch of enchantment to the picturesque scene.',
  'The old, worn-out book held within its pages a story that had captured the hearts of readers for generations.',
  'The hiker trekked up the steep mountain trail, overcome with a sense of accomplishment as they reached the summit.',
  'The bustling cafe buzzed with conversation as patrons enjoyed cups of steaming coffee and plates of delectable pastries.',
  'The enchanting melody of the violin filled the concert hall, evoking emotions that words alone could not express.',
  'The scent of freshly baked bread wafted from the bakery, drawing in passersby with its irresistible aroma.',
  'The gentle rain tapped against the windowpane, creating a soothing rhythm that lulled the weary traveler to sleep.',
  'A rainbow arched across the sky, its vibrant hues serving as a reminder of hope and beauty after the storm.',
  "The vintage car cruised along the coastal highway, the wind in the driver's hair and the sun on their face.",
  'The snow-capped mountains stood as silent guardians, their majestic peaks reaching towards the heavens.',
  "In the artist's studio, paintbrushes, and tubes of paint lay scattered across the table, evidence of creative inspiration.",
  'The eager students gathered in the classroom, eagerly awaiting the start of a fascinating lecture on astrophysics.',
  'The aroma of sizzling spices filled the air as the chef prepared a tantalizing feast of exotic cuisine.',
];
